### ISSUE TITLE
Read of uninitialized values in the speed and hashing tests

### ISSUE THREAD

**Issue by rben-dev** [mupq/mupq#149]
The input message buffer for signature is not initialized in https://github.com/mupq/mupq/blob/d5d4ed32d3016346c2c882f0ca3c951936364205/crypto_sign/speed.c#L35 and https://github.com/mupq/mupq/blob/d5d4ed32d3016346c2c882f0ca3c951936364205/crypto_sign/hashing.c#L36, meaning that on a board this will read unitialized data in SRAM (which might depend on previous flashing when the board is not cold rebooted). Although this is not a big deal when testing speed with random generation, this becomes kind of cumbersome when we expect a deterministic behavior (e.g. when we set the random bytes generation to a deterministic one).

This can easily be fixed with the following:
`unsigned char sm[MLEN+MUPQ_CRYPTO_BYTES] = { 0 };`

**Comment by mkannwischer** [comment]
You are right, we should initialize this. I think it's better to sign a random message rather than setting it to zero though.
