### ISSUE TITLE
Incorrect printf statement?

### ISSUE THREAD

**Issue by jwbos** [mupq/mupq#24]
Line 38 in mupq/crypto_kem/testvectors-host.c is
`printf(outs);`
Rightfully the compiler complains:

> mupq/crypto_kem/testvectors-host.c: In function ‘printbytes’:
> mupq/crypto_kem/testvectors-host.c:38:10: warning: format not a string literal and no format arguments [-Wformat-security]
>    printf(outs); 

Is this intended?

**Comment by Ko-** [comment]
No. Not sure how that ended up there. It's in more places too.
