### ISSUE TITLE
ThreeBears code

### ISSUE THREAD

**Issue by leonbotros** [mupq/mupq#33]
Hi, I am currently working on getting ThreeBears into PQClean. 
However, the code (found here) from ThreeBears seems to be either outdated
or producing wrong NIST KATs. It does succeed func_test though. This 
probably means something is off with cshake.

The code obtained from NIST seems to do some custom cshake initialization method.
With PQClean's hash API, this should be reproducible. 
The todo in 417b7f952caca18fad87de708fa596e5a3f6190d left here says to "replace cshake", but I can see this (or some attempt) was done already.
Did this code once produce correct KATs? Or was it abandoned?

**Comment by Ko-** [comment]
The code that is in `pqm4` is a snapshot that we received by email by mid-May. That is more recent than the code on the NIST website, although if I browse through the commits of the [ThreeBears repo](https://sourceforge.net/p/threebears/code/commit_browser) they should most likely be semantically equivalent and produce equal KATs. Although I have to admit that we never tested for this. Only that all implementations in `pqm4` match with each other. In this case: just `ref` vs. `opt`.

The ThreeBears implementation initially (in the commit with that "TODO") came with its own implementation of cSHAKE. We then decided to add cSHAKE to the common functions. (C.f. #13 and PQClean/PQclean#183.) In the commits labeled "Use sp800-185.h for ThreeBears ref/opt" I then dumped the custom cSHAKE implementation in ThreeBears and swapped in our generic implementation. The generic cSHAKE implementation in PQClean is tested against test vectors from the Keccak Code Package, but it is entirely possible that some error got introduced somewhere else  along the way.

**Comment by leonbotros** [comment]
Ok, thanks for clearing that up. The repo you mentioned seems to have switched to an implicit rejection about three months ago. Should I go for compatibility with NIST round 2 KATs or the newest version, for which no KATs seem available?

**Comment by mkannwischer** [comment]
Is this the change that was announced in https://groups.google.com/a/list.nist.gov/forum/#!searchin/pqc-forum/threebears%7Csort:date/pqc-forum/n697EbWAcAk/oE9BZPi2AQAJ ? 
Please go for the most recent version.

**Comment by leonbotros** [comment]
Yes, that change. But there repo does not contain KAT generation code. I could do this however. I'll first look into debugging why we had different KATs before so that were sure we generate the right ones.

**Comment by leonbotros** [comment]
A little followup on this. Seems both implementations are fine and your changes were fine too, @Ko- . 
One parameter was different, which gets hashed during initialization. I'll do a pull request soon, thanks for the help!
