### ISSUE TITLE
Broken Symlinks for *bear ciphers

### ISSUE THREAD

**Issue by rpls** [mupq/mupq#38]
All the symlinks for the `{mama,papa,baby}bear-ephem` ciphers seem to be broken. They reference a folder named `mamabear` (note, without `-ephem`). Even the `mamabear-ephem` cipher references this folder.

**Comment by rpls** [comment]
The PQClean repo has a `mamabear/clean` folder, but not a `mamabear/opt`, which the files reference.

**Comment by mkannwischer** [comment]
Sorry, I removed too much in 6fb7df2b84509d08866ee6c26505dd26f884a5b1. 
Also PQClean now also has the ephemeral bears, so it makes sense to take them from there. 
I'll fix this asap. 

Thanks for catching this @rpls
